name: Test passing environment varaibles between jobs

on:
  workflow_dispatch

jobs:
    get_build_agent_ip:
      name: Passing environment variables between steps and jobs
      runs-on: ubuntu-latest
      environment: test
      
      # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
      defaults:
        run:
          shell: bash
      
      steps:
        # Get IP and make available to other steps and jobs
      - name: "Get the build agent IP"
        run: | 
          echo "TF_VAR_BUILD_AGENT_IP=$(curl 'https://api.ipify.org')" >> $GITHUB_ENV

        # Show IP
      - name: "Echo the IP"
        run: | 
          echo ${{ env.TF_VAR_BUILD_AGENT_IP }}
