name: Test passing environment varaibles between jobs

on:
  workflow_dispatch

jobs:
    get_build_agent_ip:
      name: Passing environment variables between steps and jobs
      runs-on: ubuntu-latest
      env:
        AzurermBackendResourceGroupName: ${{ secrets.AZURE_ARM_BACKEND_RG }}
        AzurermBackendStorageAccountName: ${{ secrets.AZURE_ARM_BACKEND_SA }}
        AzurermBackendContainerName: ${{ secrets.AZURE_ARM_BACKEND_CONTAINER }}
        AzurermBackendBlobName: ${{ secrets.AZURE_ARM_BACKEND_BLOB }}
 
        environment: Test
      
      # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
      defaults:
        run:
          shell: bash
      
      steps:
        # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
      
        # Create Terraform Backend Config File
      - name: "Create Terraform Backend Config File"
        run: | 
          cat <<EOT  >> $GITHUB_WORKSPACE/azurerm.tfbackend
          resource_group_name  = "${{env.AZURE_BACKEND_RG_NAME}}"
          storage_account_name = "${{env.AZURE_BACKEND_SA_NAME}}"
          container_name       = "${{env.AZURE_BACKEND_CONTAINER_NAME}}" 
          key                  = "${{env.AZURE_BACKEND_BLOB_NAME}}"
          EOT
          chmod +r $GITHUB_WORKSPACE/azurerm.tfbackend
          tail $GITHUB_WORKSPACE/azurerm.tfbackend
   
        # Get IP and make available to other steps and jobs
      - name: "Check the Terraform backend config file"
        run: | 
          tail ${{env.GITHUB_WORKSPACE}}/azurerm.tfbackend
      
      # Get IP and make available to other steps and jobs
      - name: "Get the build agent IP"
        run: | 
          echo "TF_VAR_BUILD_AGENT_IP=$(curl 'https://api.ipify.org')" >> $GITHUB_ENV

        # Show IP
      - name: "Echo the IP"
        run: | 
          echo ${{ env.TF_VAR_BUILD_AGENT_IP }}
