name: Test passing environment varaibles between jobs

on:
  workflow_dispatch

jobs:
    get_build_agent_ip:
      name: Passing environment variables between steps and jobs
      runs-on: ubuntu-latest
      environment: test
      
      # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
      defaults:
        run:
          shell: bash
      
      steps:
        # Get IP and make available to other steps and jobs
      - name: "Get the build agent IP"
        run: | 
          echo "TF_VAR_BUILD_AGENT_IP=$(curl 'https://api.ipify.org')" >> $GITHUB_ENV
          $output=${{ env.TF_VAR_BUILD_AGENT_IP }}
          Write-Output "::set-output name=build_ip::$output"

    access_build_agent_ip:
      name: Accessing the build agent IP from a different job
      runs-on: ubuntu-latest
      environment: test
      
      # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
      defaults:
        run:
          shell: bash
      
      steps:
      - name: Access the environment variable from another job
        run: |
          echo "The environment varaible passed from the previous job is: ${{ needs.get_ip.output.build_ip }}"
